import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml",
    "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
# decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[scrolling]
history = 10000


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[terminal]
osc52 = "CopyPaste"
