[keyboard]
bindings =[
    { key = "a", mods = "Shift", chars = "SelectAll" },
    { key = "B", mods = "Control", chars = "ShowBookmarks" },
    { key = "C", mods = "Command", chars = "Copy" },
    { key = "F", mods = "Command", chars = "Find" },
    { key = "F", mods = "Control|Shift", chars = "ToggleFullscreen" },
    { key = "G", mods = "Control", chars = "ShowLocation" },
    { key = "H", mods = "Control", chars = "SplitHorizontal" },
    { key = "J", mods = "Control", chars = "FocusDown" },
    { key = "K", mods = "Control", chars = "FocusUp" },
    { key = "L", mods = "Control", chars = "FocusRight" },
    { key = "N", mods = "Control", chars = "NewWindow" },
    { key = "O", mods = "Control", chars = "OpenLocation" },
    { key = "P", mods = "Control", chars = "Print" },
    { key = "Q", mods = "Control", chars = "Quit" },
    { key = "R", mods = "Control", chars = "Reload" },
    { key = "S", mods = "Control", chars = "Save" },
    { key = "T", mods = "Control", chars = "NewTab" },
    { key = "U", mods = "Control", chars = "ViewSource" },
    { key = "V", mods = "Control", chars = "Paste" },
    { key = "W", mods = "Control|Shift", chars = "CloseWindow" },
    { key = "W", mods = "Control", chars = "CloseTab" },
    { key = "X", mods = "Control", chars = "Cut" },
    { key = "z" , mods = "Control", chars = "Undo" },
    { key = "y" , mods = "Control", chars = "Redo" },
    { key = "Tab", mods = "Control", chars = "NextTab" },
    { key = "Tab", mods = "Control|Shift", chars = "PrevTab" },
    { key = "PageUp", mods = "Control", chars = "ScrollPageUp" },
    { key = "PageDown", mods = "Control", chars = "ScrollPageDown" },
    { key = "Home", mods = "Control", chars = "ScrollToTop" },
    { key = "End", mods = "Control", chars = "ScrollToBottom" },
    { key = "Up", mods = "Control", chars = "ScrollUp" },
    { key = "Down", mods = "Control", chars = "ScrollDown" },
    { key = "Left", mods = "Control", chars = "ScrollLeft" },
    { key = "Right", mods = "Control", chars = "ScrollRight" },
    { key = "F5", mods = "None", chars = "Reload" },
    { key = "Return", mods = "Control", chars = "Submit" },
    { key = "Tab", mods = "Control", chars = "NextTab" },
    { key = "Tab", mods = "Control|Shift", chars = "PrevTab" },
    { key = "PageUp", mods = "Control", chars = "ScrollPageUp" },
    { key = "PageDown", mods = "Control", chars = "ScrollPageDown" },
    { key = "Home", mods = "Control", chars = "ScrollToTop" },
    { key = "End", mods = "Control", chars = "ScrollToBottom" },
    { key = "Up", mods = "Control", chars = "ScrollUp" },
    { key = "Down", mods = "Control", chars = "ScrollDown" },
    { key = "Left", mods = "Control", chars = "ScrollLeft" },
    { key = "Right", mods = "Control", chars = "ScrollRight" },
    { key = "F5", mods = "None", chars = "Reload" },
    { key = "Return", mods = "Control", chars = "Submit" },
  ]
